% -------------------------------------------------------------------
%  Generated by MATLAB on 22-Apr-2021 14:10:33
%  MATLAB version: 9.6.0.1072779 (R2019a)
% -------------------------------------------------------------------
saveVarsMat = load('no1matriks.mat');

A = ...
  [3 7 3 1 8 3;
   5 10 8 4 2 5;
   9 6 20 13 -3 11;
   12 9 5 2 7 6;
   4 2 7 7 9 12;
   -9 1 9 -5 14 4];

Matriks_2 = ...
  [3 10 20 2 9 4;
   -9 2 5 13 2 3];

ans = ...
  [10 8;
   6 20;
   9 5];

no1a = saveVarsMat.no1a; % <1x1 table> unsupported class

clear saveVarsMat;
